#!/bin/sh

set -ue
record=false

for opt; do
  case $opt in
    --record) record=true ;;
    *) echo >&2 "usage: $0 [--record]"; exit 2 ;;
  esac
done

prompt() {
  echo -n ">>> $* "
  read -r res
  "$@" && echo
}

clear
if $record; then
  echo "Starting recording."
  pamixer --source @DEFAULT_SOURCE@ --set-volume 100
  wf-recorder -a -f screencast.mp4 -o eDP-1 -y > /tmp/screencast.log 2>&1 & pid=$!
  trap 'kill -INT $pid 2> /dev/null && wait' EXIT INT
else
  echo "Not recording. Pass --record to start screencast."
fi

sleep 1
neovide --no-tabs -- -M MemoryManager/MemoryManager.h MemoryManager/MemoryManager.cpp
prompt make -B test.out
prompt valgrind ./test.out
echo -n "Press Enter to end recording. "
read -r res
